SET IDENTITY_INSERT [dbo].[SubCategories] ON
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (0, N'Xbox1', N'1', 3)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (1, N'Switch', N'2', 3)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (2, N'PS4', N'3', 3)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (3, N'Bordspellen', N'4', 0)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (4, N'Kaartspellen', N'5', 0)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (5, N'Partyspellen', N'6', 0)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (6, N'Kinderpuzzels', N'7', 4)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (7, N'3D puzzels', N'8', 4)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (8, N'Barbie', N'9', 1)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (9, N'Baby-born', N'0', 1)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (10, N'Poppenhuis', N'10', 1)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (11, N'Speelauto''s en racebanen', N'11', 2)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (12, N'Garages', N'12', 2)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (13, N'Treinen en treinbanen', N'13', 2)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (14, N'Drones', N'14', 2)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (15, N'Kleurboeken', N'15', 7)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (16, N'Prentenboeken', N'16', 7)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (17, N'Fictie boeken', N'17', 7)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (18, N'Bijtringen en rammelaars', N'18', 9)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (19, N'Badspeelgoed', N'19', 9)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (20, N'Stapelspeelgoed', N'20', 9)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (21, N'Vormpjesspeelgoed', N'21', 9)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (22, N'Overig babyspeelgoed', N'22', 9)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (23, N'LEGO city', N'23', 5)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (24, N'LEGO Ninjago', N'24', 5)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (25, N'LEGO Duplo', N'25', 5)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (26, N'K''nex', N'26', 6)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (27, N'BRIO', N'27', 6)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (28, N'Speeltoestellen', N'28', 10)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (29, N'Zandspeelgoed', N'29', 10)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (30, N'Zwembaden', N'30', 10)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (31, N'Rijden speelgoed', N'31', 10)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (32, N'Knutselpakketten', N'32', 8)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (33, N'Tekenen', N'33', 8)
INSERT INTO [dbo].[SubCategories] ([SubCategoryId], [SubCategoryName], [Description], [CategoryId]) VALUES (34, N'Schilderen', N'34', 8)
SET IDENTITY_INSERT [dbo].[SubCategories] OFF
