//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toymania.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Coupon
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        public string Code { get; set; }
        [Range(0.01, 1000, ErrorMessage = "price Must be between 0.01 and 1000")]
        public decimal Value { get; set; }
        public bool Used { get; set; }
    }
}
