//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toymania.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [ScaffoldColumn(false)]
        public int OrderId { get; set; }
        [ScaffoldColumn(false)]
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        //[ScaffoldColumn(false)]
        //public string Email { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<decimal> Total { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<int> year { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<int> month { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<int> day { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<int> minute { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<int> second { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<int> hour { get; set; }
        [ScaffoldColumn(false)]
        public Nullable<int> week { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
