//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toymania.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using Toymania.Models;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Wishlist
    {
        public int WishlistId { get; set; }
        public string Email { get; set; }
        public Nullable<int> ToysId { get; set; }
    
        public virtual Toy Toy { get; set; }
    }
}
