// <auto-generated />
namespace Toymania.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tse43 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tse43));
        
        string IMigrationMetadata.Id
        {
            get { return "201901081912035_tse43"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
