// <auto-generated />
namespace Toymania.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tse41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tse41));
        
        string IMigrationMetadata.Id
        {
            get { return "201901081902271_tse41"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
